[phases.setup]
nixPkgs = [
  "php81",
  "php81Packages.composer",
  "nodejs",
  "mysql",
  "php81Extensions.fileinfo",
  "php81Extensions.pdo",
  "php81Extensions.pdo_mysql"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install --production",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]
